<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Occupation Fields (main categories)
    |--------------------------------------------------------------------------
    */
    'fields' => [
        'en' => [
            '' => '--- Choose a Field ---',
            'medical' => 'Medical',
            'pharmacy' => 'Pharmacy',
            'military' => 'Military / Army',
            'education' => 'Education & Teaching',
            'it' => 'Information Technology',
            'engineering' => 'Engineering',
            'law' => 'Law',
            'finance' => 'Finance & Accounting',
            'administration' => 'Administration & Management',
            'agriculture' => 'Agriculture',
            'art' => 'Art & Design',
            'media' => 'Media & Communication',
            'construction' => 'Construction & Architecture',
        ],
        'fr' => [
            '' => '--- Choisissez un domaine ---',
            'medical' => 'Médical',
            'pharmacy' => 'Pharmacie',
            'military' => 'Militaire / Armée',
            'education' => 'Éducation & Enseignement',
            'it' => 'Technologies de l\'information',
            'engineering' => 'Ingénierie',
            'law' => 'Droit',
            'finance' => 'Finance & Comptabilité',
            'administration' => 'Administration & Gestion',
            'agriculture' => 'Agriculture',
            'art' => 'Art & Design',
            'media' => 'Médias & Communication',
            'construction' => 'Construction & Architecture',
        ],
        'ar' => [
            '' => '--- اختر مجالًا ---',
            'medical' => 'الطب',
            'pharmacy' => 'الصيدلة',
            'military' => 'العسكرية / الجيش',
            'education' => 'التعليم والتدريس',
            'it' => 'تكنولوجيا المعلومات',
            'engineering' => 'الهندسة',
            'law' => 'القانون',
            'finance' => 'المالية والمحاسبة',
            'administration' => 'الإدارة',
            'agriculture' => 'الزراعة',
            'art' => 'الفن والتصميم',
            'media' => 'الإعلام والاتصال',
            'construction' => 'البناء والهندسة المعمارية',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Specialties by Field
    |--------------------------------------------------------------------------
    | Only defined for 'medical' field now; can add others similarly.
    */
    'specialties_by_field' => [
        'medical' => [
            'en' => [
                '' => '--- Choose a Specialty ---',
                'allergology' => 'Allergology',
                'anesthesiology' => 'Anesthesiology',
                'andrology' => 'Andrology',
                'cardiology' => 'Cardiology',
                'cardiac_surgery' => 'Cardiac Surgery',
                'aesthetic_plastic_reconstructive_surgery' => 'Aesthetic, Plastic, and Reconstructive Surgery',
                'general_surgery' => 'General Surgery',
                'maxillofacial_surgery' => 'Maxillofacial Surgery',
                'pediatric_surgery' => 'Pediatric Surgery',
                'thoracic_surgery' => 'Thoracic Surgery',
                'vascular_surgery' => 'Vascular Surgery',
                'neurosurgery' => 'Neurosurgery',
                'dermatology' => 'Dermatology',
                'endocrinology' => 'Endocrinology',
                'gastroenterology' => 'Gastroenterology',
                'geriatrics' => 'Geriatrics',
                'obstetrics_gynecology' => 'Obstetrics and Gynecology',
                'hematology' => 'Hematology',
                'hepatology' => 'Hepatology',
                'infectious_diseases' => 'Infectious Diseases',
                'occupational_medicine' => 'Occupational Medicine',
                'nuclear_medicine' => 'Nuclear Medicine',
                'neonatology' => 'Neonatology',
                'nephrology' => 'Nephrology',
                'neurology' => 'Neurology',
                'dentistry' => 'Dentistry',
                'oncology' => 'Oncology',
                'ophthalmology' => 'Ophthalmology',
                'orthopedics' => 'Orthopedics',
                'pediatrics' => 'Pediatrics',
                'pulmonology' => 'Pulmonology',
                'radiology' => 'Radiology',
                'radiotherapy' => 'Radiotherapy',
                'rheumatology' => 'Rheumatology',
                'urology' => 'Urology',
            ],
            'fr' => [
                '' => '--- Choisissez une spécialité ---',
                'allergology' => 'Allergologie',
                'anesthesiology' => 'Anesthésiologie',
                'andrology' => 'Andrologie',
                'cardiology' => 'Cardiologie',
                'cardiac_surgery' => 'Chirurgie cardiaque',
                'aesthetic_plastic_reconstructive_surgery' => 'Chirurgie plastique esthétique et reconstructrice',
                'general_surgery' => 'Chirurgie générale',
                'maxillofacial_surgery' => 'Chirurgie maxillo-faciale',
                'pediatric_surgery' => 'Chirurgie pédiatrique',
                'thoracic_surgery' => 'Chirurgie thoracique',
                'vascular_surgery' => 'Chirurgie vasculaire',
                'neurosurgery' => 'Neurochirurgie',
                'dermatology' => 'Dermatologie',
                'endocrinology' => 'Endocrinologie',
                'gastroenterology' => 'Gastro-entérologie',
                'geriatrics' => 'Gériatrie',
                'obstetrics_gynecology' => 'Obstétrique et gynécologie',
                'hematology' => 'Hématologie',
                'hepatology' => 'Hépatologie',
                'infectious_diseases' => 'Maladies infectieuses',
                'occupational_medicine' => 'Médecine du travail',
                'nuclear_medicine' => 'Médecine nucléaire',
                'neonatology' => 'Néonatologie',
                'nephrology' => 'Néphrologie',
                'neurology' => 'Neurologie',
                'dentistry' => 'Dentisterie',
                'oncology' => 'Oncologie',
                'ophthalmology' => 'Ophtalmologie',
                'orthopedics' => 'Orthopédie',
                'pediatrics' => 'Pédiatrie',
                'pulmonology' => 'Pneumologie',
                'radiology' => 'Radiologie',
                'radiotherapy' => 'Radiothérapie',
                'rheumatology' => 'Rhumatologie',
                'urology' => 'Urologie',
            ],
            'ar' => [
                '' => '--- اختر تخصصًا ---',
                'allergology' => 'الحساسية والمناعة',
                'anesthesiology' => 'علم التخدير',
                'andrology' => 'علم الذكورة',
                'cardiology' => 'طب القلب',
                'cardiac_surgery' => 'جراحة القلب',
                'aesthetic_plastic_reconstructive_surgery' => 'جراحة التجميل والترميمية',
                'general_surgery' => 'جراحة عامة',
                'maxillofacial_surgery' => 'جراحة الفك والوجه',
                'pediatric_surgery' => 'جراحة الأطفال',
                'thoracic_surgery' => 'جراحة الصدر',
                'vascular_surgery' => 'جراحة الأوعية الدموية',
                'neurosurgery' => 'جراحة الأعصاب',
                'dermatology' => 'طب الأمراض الجلدية',
                'endocrinology' => 'علم الغدد الصماء',
                'gastroenterology' => 'الجهاز الهضمي',
                'geriatrics' => 'طب المسنين',
                'obstetrics_gynecology' => 'طب النساء والتوليد',
                'hematology' => 'علم الدم',
                'hepatology' => 'علم الكبد',
                'infectious_diseases' => 'الأمراض المعدية',
                'occupational_medicine' => 'الطب الوظيفي',
                'nuclear_medicine' => 'الطب النووي',
                'neonatology' => 'طب حديثي الولادة',
                'nephrology' => 'علم الكلى',
                'neurology' => 'طب الأعصاب',
                'dentistry' => 'طب الأسنان',
                'oncology' => 'علم الأورام',
                'ophthalmology' => 'طب العيون',
                'orthopedics' => 'طب العظام',
                'pediatrics' => 'طب الأطفال',
                'pulmonology' => 'أمراض الرئة',
                'radiology' => 'الأشعة التشخيصية',
                'radiotherapy' => 'العلاج الإشعاعي',
                'rheumatology' => 'أمراض المفاصل',
                'urology' => 'المسالك البولية',
            ],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Grades by Field
    |--------------------------------------------------------------------------
    */
    'grades_by_field' => [
        'medical' => [
            'en' => [
                '' => '--- Choose a Grade ---',
                'intern' => 'Intern',
                'resident' => 'Resident',
                'senior_resident' => 'Senior Resident',
                'specialist' => 'Specialist',
                'senior_specialist' => 'Senior Specialist',
                'consultant' => 'Consultant',
                'senior_consultant' => 'Senior Consultant',
                'head_of_department' => 'Head of Department',
                'chief_medical_officer' => 'Chief Medical Officer',
            ],
            'fr' => [
                '' => '--- Choisissez un grade ---',
                'intern' => 'Interne',
                'resident' => 'Résident',
                'senior_resident' => 'Résident senior',
                'specialist' => 'Spécialiste',
                'senior_specialist' => 'Spécialiste senior',
                'consultant' => 'Consultant',
                'senior_consultant' => 'Consultant senior',
                'head_of_department' => 'Chef de service',
                'chief_medical_officer' => 'Directeur médical',
            ],
            'ar' => [
                '' => '--- اختر الدرجة ---',
                'intern' => 'متدرب',
                'resident' => 'طبيب مقيم',
                'senior_resident' => 'طبيب مقيم أول',
                'specialist' => 'اختصاصي',
                'senior_specialist' => 'اختصاصي أول',
                'consultant' => 'استشاري',
                'senior_consultant' => 'استشاري أول',
                'head_of_department' => 'رئيس القسم',
                'chief_medical_officer' => 'المدير الطبي',
            ],
        ],
    ],

];
